/**
 * Action Types
 */
export const GROUPS_GETALL = 'GROUPS_GETALL';
export const GROUPS_GETALL_START = 'GROUPS_GETALL_START';
export const GROUPS_GETALL_SUCCESS = 'GROUPS_GETALL_SUCCESS';
export const GROUPS_GETALL_RESPONSE = 'GROUPS_GETALL_RESPONSE';
export const GROUPS_GETALL_FAILURE = 'GROUPS_GETALL_FAILURE';

export const GROUPS_SAVE = 'GROUPS_SAVE';
export const GROUPS_SAVE_START = 'GROUPS_SAVE_START';
export const GROUPS_SAVE_SUCCESS = 'GROUPS_SAVE_SUCCESS';
export const GROUPS_SAVE_RESPONSE = 'GROUPS_SAVE_RESPONSE';
export const GROUPS_SAVE_FAILURE = 'GROUPS_SAVE_FAILURE';

export const GROUPS_GETBYID = 'GROUPS_GETBYID';
export const GROUPS_GETBYID_START = 'GROUPS_GETBYID_START';
export const GROUPS_GETBYID_SUCCESS = 'GROUPS_GETBYID_SUCCESS';
export const GROUPS_GETBYID_RESPONSE = 'GROUPS_GETBYID_RESPONSE';
export const GROUPS_GETBYID_FAILURE = 'GROUPS_GETBYID_FAILURE';
export const GROUPS_GETBYID_END = 'GROUPS_GETBYID_END';

export const GROUPS_GET_COMMENTS = 'GROUPS_GET_COMMENTS';
export const GROUPS_GET_COMMENTS_START = 'GROUPS_GET_COMMENTS_START';
export const GROUPS_GET_COMMENTS_SUCCESS = 'GROUPS_GET_COMMENTS_SUCCESS';
export const GROUPS_GET_COMMENTS_RESPONSE = 'GROUPS_GET_COMMENTS_RESPONSE';
export const GROUPS_GET_COMMENTS_FAILURE = 'GROUPS_GET_COMMENTS_FAILURE';

export const GROUPS_SAVE_COMMENT = 'GROUPS_SAVE_COMMENT';
export const GROUPS_SAVE_COMMENT_START = 'GROUPS_SAVE_COMMENT_START';
export const GROUPS_SAVE_COMMENT_SUCCESS = 'GROUPS_SAVE_COMMENT_SUCCESS';
export const GROUPS_SAVE_COMMENT_RESPONSE = 'GROUPS_SAVE_COMMENT_RESPONSE';
export const GROUPS_SAVE_COMMENT_FAILURE = 'GROUPS_SAVE_COMMENT_FAILURE';

export const GROUPS_GET_LOCATIONS = 'GROUPS_GET_LOCATIONS';
export const GROUPS_GET_LOCATIONS_START = 'GROUPS_GET_LOCATIONS_START';
export const GROUPS_GET_LOCATIONS_SUCCESS = 'GROUPS_GET_LOCATIONS_SUCCESS';
export const GROUPS_GET_LOCATIONS_RESPONSE = 'GROUPS_GET_LOCATIONS_RESPONSE';
export const GROUPS_GET_LOCATIONS_FAILURE = 'GROUPS_GET_LOCATIONS_FAILURE';

export const GROUPS_GET_PEOPLE_GROUPS = 'GROUPS_GET_PEOPLE_GROUPS';
export const GROUPS_GET_PEOPLE_GROUPS_START = 'GROUPS_GET_PEOPLE_GROUPS_START';
export const GROUPS_GET_PEOPLE_GROUPS_SUCCESS = 'GROUPS_GET_PEOPLE_GROUPS_SUCCESS';
export const GROUPS_GET_PEOPLE_GROUPS_RESPONSE = 'GROUPS_GET_PEOPLE_GROUPS_RESPONSE';
export const GROUPS_GET_PEOPLE_GROUPS_FAILURE = 'GROUPS_GET_PEOPLE_GROUPS_FAILURE';

export const GROUPS_GET_ACTIVITIES = 'GROUPS_GET_ACTIVITIES';
export const GROUPS_GET_ACTIVITIES_START = 'GROUPS_GET_ACTIVITIES_START';
export const GROUPS_GET_ACTIVITIES_SUCCESS = 'GROUPS_GET_ACTIVITIES_SUCCESS';
export const GROUPS_GET_ACTIVITIES_RESPONSE = 'GROUPS_GET_ACTIVITIES_RESPONSE';
export const GROUPS_GET_ACTIVITIES_FAILURE = 'GROUPS_GET_ACTIVITIES_FAILURE';

export const GROUPS_GET_SETTINGS = 'GROUPS_GET_SETTINGS';
export const GROUPS_GET_SETTINGS_START = 'GROUPS_GET_SETTINGS_START';
export const GROUPS_GET_SETTINGS_SUCCESS = 'GROUPS_GET_SETTINGS_SUCCESS';
export const GROUPS_GET_SETTINGS_RESPONSE = 'GROUPS_GET_SETTINGS_RESPONSE';
export const GROUPS_GET_SETTINGS_FAILURE = 'GROUPS_GET_SETTINGS_FAILURE';

export const GROUPS_LOCATIONS_SEARCH = 'GROUPS_LOCATIONS_SEARCH';
export const GROUPS_LOCATIONS_SEARCH_START = 'GROUPS_LOCATIONS_SEARCH_START';
export const GROUPS_LOCATIONS_SEARCH_SUCCESS = 'GROUPS_LOCATIONS_SEARCH_SUCCESS';
export const GROUPS_LOCATIONS_SEARCH_RESPONSE = 'GROUPS_LOCATIONS_SEARCH_RESPONSE';
export const GROUPS_LOCATIONS_SEARCH_FAILURE = 'GROUPS_LOCATIONS_SEARCH_FAILURE';

export const GROUPS_LOCATIONS_MODIFIED_DATE = 'GROUPS_LOCATIONS_MODIFIED_DATE';
export const GROUPS_LOCATIONS_MODIFIED_DATE_START = 'GROUPS_LOCATIONS_MODIFIED_DATE_START';
export const GROUPS_LOCATIONS_MODIFIED_DATE_SUCCESS = 'GROUPS_LOCATIONS_MODIFIED_DATE_SUCCESS';
export const GROUPS_LOCATIONS_MODIFIED_DATE_RESPONSE = 'GROUPS_LOCATIONS_MODIFIED_DATE_RESPONSE';
export const GROUPS_LOCATIONS_MODIFIED_DATE_FAILURE = 'GROUPS_LOCATIONS_MODIFIED_DATE_FAILURE';

export const GROUPS_DELETE_COMMENT = 'GROUPS_DELETE_COMMENT';
export const GROUPS_DELETE_COMMENT_START = 'GROUPS_DELETE_COMMENT_START';
export const GROUPS_DELETE_COMMENT_SUCCESS = 'GROUPS_DELETE_COMMENT_SUCCESS';
export const GROUPS_DELETE_COMMENT_RESPONSE = 'GROUPS_DELETE_COMMENT_RESPONSE';
export const GROUPS_DELETE_COMMENT_FAILURE = 'GROUPS_DELETE_COMMENT_FAILURE';

export const GROUPS_LOADING_FALSE = 'GROUPS_LOADING_FALSE';
export const GROUPS_UPDATE_PREVIOUS = 'GROUPS_UPDATE_PREVIOUS';

export const GROUPS_GET_SHARE_SETTINGS = 'GROUPS_GET_SHARE_SETTINGS';
export const GROUPS_GET_SHARE_SETTINGS_START = 'GROUPS_GET_SHARE_SETTINGS_START';
export const GROUPS_GET_SHARE_SETTINGS_RESPONSE = 'GROUPS_GET_SHARE_SETTINGS_RESPONSE';
export const GROUPS_GET_SHARE_SETTINGS_SUCCESS = 'GROUPS_GET_SHARE_SETTINGS_SUCCESS';
export const GROUPS_GET_SHARE_SETTINGS_FAILURE = 'GROUPS_GET_SHARE_SETTINGS_FAILURE';

export const GROUPS_ADD_USER_SHARE = 'GROUPS_ADD_USER_SHARE';
export const GROUPS_ADD_USER_SHARE_START = 'GROUPS_ADD_USER_SHARE_START';
export const GROUPS_ADD_USER_SHARE_RESPONSE = 'GROUPS_ADD_USER_SHARE_RESPONSE';
export const GROUPS_ADD_USER_SHARE_SUCCESS = 'GROUPS_ADD_USER_SHARE_SUCCESS';
export const GROUPS_ADD_USER_SHARE_FAILURE = 'GROUPS_ADD_USER_SHARE_FAILURE';

export const GROUPS_REMOVE_SHARED_USER = 'GROUPS_REMOVE_SHARED_USER';
export const GROUPS_REMOVE_SHARED_USER_START = 'GROUPS_REMOVE_SHARED_USER_START';
export const GROUPS_REMOVE_SHARED_USER_RESPONSE = 'GROUPS_REMOVE_SHARED_USER_RESPONSE';
export const GROUPS_REMOVE_SHARED_USER_SUCCESS = 'GROUPS_REMOVE_SHARED_USER_SUCCESS';
export const GROUPS_REMOVE_SHARED_USER_FAILURE = 'GROUPS_REMOVE_SHARED_USER_FAILURE';

/**
 * Action Creators
 */

/**
 *
 * @param {*} filter { offset: number, limit: number, sort: string, name?: string, ...optionFilter }
 */
export function getAll(filter) {
  return {
    type: GROUPS_GETALL,
    filter,
  };
}

export function saveGroup(groupData) {
  return {
    type: GROUPS_SAVE,
    groupData,
  };
}

export function getById(groupId) {
  return {
    type: GROUPS_GETBYID,
    groupId,
  };
}

export function getByIdEnd() {
  return {
    type: GROUPS_GETBYID_END,
  };
}

export function getCommentsByGroup(groupId, pagination) {
  return {
    type: GROUPS_GET_COMMENTS,
    groupId,
    pagination,
  };
}

export function saveComment(groupId, commentData) {
  return {
    type: GROUPS_SAVE_COMMENT,
    groupId,
    commentData,
  };
}

export function getLocations() {
  return {
    type: GROUPS_GET_LOCATIONS,
  };
}

export function getPeopleGroups() {
  return {
    type: GROUPS_GET_PEOPLE_GROUPS,
  };
}

export function getActivitiesByGroup(groupId, pagination) {
  return {
    type: GROUPS_GET_ACTIVITIES,
    groupId,
    pagination,
  };
}

export function getGroupSettings() {
  return {
    type: GROUPS_GET_SETTINGS,
  };
}

export function searchLocations(queryText) {
  return {
    type: GROUPS_LOCATIONS_SEARCH,
    queryText,
  };
}

export function getLocationListLastModifiedDate() {
  return {
    type: GROUPS_LOCATIONS_MODIFIED_DATE,
  };
}

export function deleteComment(groupId, commentId) {
  return {
    type: GROUPS_DELETE_COMMENT,
    groupId,
    commentId,
  };
}

export function loadingFalse() {
  return {
    type: GROUPS_LOADING_FALSE,
  };
}

export function updatePrevious(previousGroups) {
  return {
    type: GROUPS_UPDATE_PREVIOUS,
    previousGroups,
  };
}

export function getShareSettings(groupId) {
  return {
    type: GROUPS_GET_SHARE_SETTINGS,
    groupId,
  };
}

export function addUserToShare(groupId, userId) {
  return {
    type: GROUPS_ADD_USER_SHARE,
    groupId,
    userId,
  };
}

export function removeUserToShare(groupId, userId) {
  return {
    type: GROUPS_REMOVE_SHARED_USER,
    groupId,
    userId,
  };
}
