/*
 * Action Types
 */

export const NOTIFICATIONS_BY_USER = 'NOTIFICATIONS_BY_USER';
export const NOTIFICATIONS_BY_USER_START = 'NOTIFICATIONS_BY_USER_START';
export const NOTIFICATIONS_BY_USER_RESPONSE = 'NOTIFICATIONS_BY_USER_RESPONSE';
export const NOTIFICATIONS_BY_USER_SUCCESS = 'NOTIFICATIONS_BY_USER_SUCCESS';
export const NOTIFICATIONS_BY_USER_FAILURE = 'NOTIFICATIONS_BY_USER_FAILURE';

export const NOTIFICATIONS_COUNT_BY_USER = 'NOTIFICATIONS_COUNT_BY_USER';
export const NOTIFICATIONS_COUNT_BY_USER_START = 'NOTIFICATIONS_COUNT_BY_USER_START';
export const NOTIFICATIONS_COUNT_BY_USER_RESPONSE = 'NOTIFICATIONS_COUNT_BY_USER_RESPONSE';
export const NOTIFICATIONS_COUNT_BY_USER_SUCCESS = 'NOTIFICATIONS_COUNT_BY_USER_SUCCESS';
export const NOTIFICATIONS_COUNT_BY_USER_FAILURE = 'NOTIFICATIONS_COUNT_BY_USER_FAILURE';

export const NOTIFICATIONS_MARK_AS_VIEWED = 'NOTIFICATIONS_MARK_AS_VIEWED';
export const NOTIFICATIONS_MARK_AS_VIEWED_START = 'NOTIFICATIONS_MARK_AS_VIEWED_START';
export const NOTIFICATIONS_MARK_AS_VIEWED_RESPONSE = 'NOTIFICATIONS_MARK_AS_VIEWED_RESPONSE';
export const NOTIFICATIONS_MARK_AS_VIEWED_SUCCESS = 'NOTIFICATIONS_MARK_AS_VIEWED_SUCCESS';
export const NOTIFICATIONS_MARK_AS_VIEWED_FAILURE = 'NOTIFICATIONS_MARK_AS_VIEWED_FAILURE';

export const NOTIFICATIONS_MARK_AS_UNREAD = 'NOTIFICATIONS_MARK_AS_UNREAD';
export const NOTIFICATIONS_MARK_AS_UNREAD_START = 'NOTIFICATIONS_MARK_AS_UNREAD_START';
export const NOTIFICATIONS_MARK_AS_UNREAD_RESPONSE = 'NOTIFICATIONS_MARK_AS_UNREAD_RESPONSE';
export const NOTIFICATIONS_MARK_AS_UNREAD_SUCCESS = 'NOTIFICATIONS_MARK_AS_UNREAD_SUCCESS';
export const NOTIFICATIONS_MARK_AS_UNREAD_FAILURE = 'NOTIFICATIONS_MARK_AS_UNREAD_FAILURE';

export const NOTIFICATIONS_MARK_ALL_AS_READ = 'NOTIFICATIONS_MARK_ALL_AS_READ';
export const NOTIFICATIONS_MARK_ALL_AS_READ_START = 'NOTIFICATIONS_MARK_ALL_AS_READ_START';
export const NOTIFICATIONS_MARK_ALL_AS_READ_RESPONSE = 'NOTIFICATIONS_MARK_ALL_AS_READ_RESPONSE';
export const NOTIFICATIONS_MARK_ALL_AS_READ_SUCCESS = 'NOTIFICATIONS_MARK_ALL_AS_READ_SUCCESS';
export const NOTIFICATIONS_MARK_ALL_AS_READ_FAILURE = 'NOTIFICATIONS_MARK_ALL_AS_READ_FAILURE';

/*
 * Action Creators
 */
export function getAll(domain, token, allNotifications, offset, limit) {
  return {
    type: NOTIFICATIONS_BY_USER,
    domain,
    token,
    allNotifications,
    offset,
    limit,
  };
}

export function getNotificationsCount(domain, token) {
  return {
    type: NOTIFICATIONS_COUNT_BY_USER,
    domain,
    token,
  };
}

export function markViewed(domain, token, notificationId) {
  return {
    type: NOTIFICATIONS_MARK_AS_VIEWED,
    domain,
    token,
    notificationId,
  };
}

export function markUnread(domain, token, notificationId) {
  return {
    type: NOTIFICATIONS_MARK_AS_UNREAD,
    domain,
    token,
    notificationId,
  };
}

export function markAllAsRead(domain, token, userID) {
  return {
    type: NOTIFICATIONS_MARK_ALL_AS_READ,
    domain,
    token,
    userID,
  };
}
