name: CI/CD

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  publish:
    name: CI/CD
    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.check_step.outputs.branch }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      #- uses: microsoft/variable-substitution@v1
      #  with:
      #    files: './app.json'
      #  env:
      #    expo.hooks.postPublish.0.config.authToken: ${{ secrets.SENTRY_AUTH_TOKEN }}
      - uses: microsoft/variable-substitution@v1
        with:
          files: './google-services.json'
        env:
          project_info.project_number: ${{ secrets.FIREBASE_PROJECT_NUMBER }}
          client.0.client_info.mobilesdk_app_id: ${{ secrets.FIREBASE_MOBILESDK_APP_ID }}
          client.0.oauth_client.0.client_id: ${{ secrets.FIREBASE_OAUTH_CLIENT_ID }}
          client.0.api_key.0.current_key: ${{ secrets.FIREBASE_API_KEY }}
          client.0.services.appinvite_service.other_platform_oauth_client.0.client_id: ${{ secrets.FIREBASE_OAUTH_CLIENT_ID }}
      #- run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: npm ci
      #- run: npm test
      - name: Get Current Branch
        id: check_step
        run: |
          raw=$(git branch -r --contains ${{ github.ref }})
          branch=${raw##*/}
          echo "::set-output name=branch::$branch"
      - name: Build on EAS and Publish to Production Channel
        if: steps.check_step.outputs.branch == 'main'
        run: eas build --platform all --non-interactive && expo publish --release-channel production 
      - name: Publish to Release Channel
        if: steps.check_step.outputs.branch == 'release'
        run: expo publish --release-channel release
      - name: Publish to Test Channel
        if: steps.check_step.outputs.branch == 'development'
        run: expo publish
