name: CI/CD

on:
  push:
    tags:
    - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  publish:
    name: CI/CD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: npm
      #- uses: microsoft/variable-substitution@v1
      #  with:
      #    files: './app.json'
      #  env:
      #    expo.hooks.postPublish.0.config.authToken: ${{ secrets.SENTRY_AUTH_TOKEN }}
      - uses: microsoft/variable-substitution@v1
        with:
          files: './google-services.json'
        env:
          project_info.project_number: ${{ secrets.FIREBASE_PROJECT_NUMBER }}
          client.0.client_info.mobilesdk_app_id: ${{ secrets.FIREBASE_MOBILESDK_APP_ID }}
          client.0.oauth_client.0.client_id: ${{ secrets.FIREBASE_OAUTH_CLIENT_ID }}
          client.0.api_key.0.current_key: ${{ secrets.FIREBASE_API_KEY }}
          client.0.services.appinvite_service.other_platform_oauth_client.0.client_id: ${{ secrets.FIREBASE_OAUTH_CLIENT_ID }}
      #- run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - name: Setup Expo and EAS
        uses: expo/expo-github-action@v7
        with:
          expo-version: 5.x
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}
      - name: Install dependencies
        run: npm ci
      #- run: npm test
      - name: Build on EAS and Publish to Production
        if: ${{ github.ref == 'refs/heads/main' }}
        run: eas build --platform all --non-interactive && expo publish --release-channel production 
      - name: Deploy Release
        if: ${{ github.ref == 'refs/heads/release' }}
        run: expo publish --release-channel release
      - name: Deploy Test
        if: ${{ github.ref == 'refs/heads/development' }}
        run: expo publish
