name: CI/CD
on:
  push:
    branches:
      - main
      - release
      - development
jobs:
  publish:
    name: CI/CD
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v1
        with:
          node-version: 12.x
      #- uses: microsoft/variable-substitution@v1
      #  with:
      #    files: './app.json'
      #  env:
      #    expo.hooks.postPublish.0.config.authToken: ${{ secrets.SENTRY_AUTH_TOKEN }}
      - uses: microsoft/variable-substitution@v1
        with:
          files: './google-services.json'
        env:
          project_info.project_number: ${{ secrets.FIREBASE_PROJECT_NUMBER }}
          client.0.client_info.mobilesdk_app_id: ${{ secrets.FIREBASE_MOBILESDK_APP_ID }}
          client.0.oauth_client.0.client_id: ${{ secrets.FIREBASE_OAUTH_CLIENT_ID }}
          client.0.api_key.0.current_key: ${{ secrets.FIREBASE_API_KEY }}
          client.0.services.appinvite_service.other_platform_oauth_client.0.client_id: ${{ secrets.FIREBASE_OAUTH_CLIENT_ID }}
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 3.x
          expo-username: ${{ secrets.EXPO_CLI_USERNAME }}
          expo-password: ${{ secrets.EXPO_CLI_PASSWORD }}
      - run: echo fs.inotify.max_user_watches=524288 | sudo tee -a /etc/sysctl.conf && sudo sysctl -p
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      - run: npm install
      - run: npm test
      - name: Deploy Prod
        if: github.ref == 'refs/heads/main'
        run: expo publish --release-channel production && expo build:ios --release-channel production --non-interactive && expo build:android --type app-bundle --release-channel production --non-interactive
      - name: Deploy Release
        if: github.ref == 'refs/heads/release'
        run: expo publish --release-channel release
      - name: Deploy Test
        if: github.ref == 'refs/heads/development'
        run: expo publish
